### ISSUE TITLE
Install Latest Playwrite go get tests working?

### ISSUE THREAD

**Issue by ardalis** [martincostello/dotnet-minimal-api-integration-testing#172]
Just cloned the app and am running it in latest VS2022 preview. Most tests pass but two fail:

![image](https://user-images.githubusercontent.com/782127/136258254-ad101e7b-cba3-4b64-a98d-85c0967715a3.png)

I follow the instructions (in the error message), but they don't succeed:

![image](https://user-images.githubusercontent.com/782127/136258321-b4463f3c-65a0-4a3e-9311-b1eb8f002d50.png)

It's great the test failure offers some tips but they don't work and ideally if it needs updated things then it should just go and get them itself, I would think. Otherwise there's no way this set of tests would work consistently in a CI process. I have no experience with Playwrite so apologies if this is all stuff any Playwrite user should know. Thanks!

**Comment by martincostello** [comment]
Yeah, previous versions of playwright (note the spelling, it's not "write") would auto-magically install all the required drivers and it was great and super-simple, but then they added the requirement to install a .NET global tool and it got slightly less awesome.

It might be that my attempts to guide people in the right direction to install it on first install/run via compiler warnings isn't good/noticeable enough:

https://github.com/martincostello/dotnet-minimal-api-integration-testing/blob/5b6e0fca3d9f8c06e2cfdade19d9306260b33dec/tests/TodoApp.Tests/TodoApp.Tests.csproj#L38-L48

In (my) CI, this is catered for by this step here:

https://github.com/martincostello/dotnet-minimal-api-integration-testing/blob/5b6e0fca3d9f8c06e2cfdade19d9306260b33dec/.github/workflows/build.yml#L38-L41

If you have any suggestions on how I can make this easier/more intuitive/obvious I'd be happy to look at some changes to make it more likely to fall into the pit of success.

**Comment by programatt** [comment]
Unfortunately Playwright doesn't appear to support dotnet 6 in the dotnet global tool. It's asking for NET 5.0 which there are no builds for on the new M1 MacBooks :(

**Comment by martincostello** [comment]
@programatt Might be worth logging that with the playwright team, or adding to this issue I raised with them to add a `net6.0` TFM: https://github.com/microsoft/playwright-dotnet/issues/1668

**Comment by martincostello** [comment]
You can also try this hack locally:

https://github.com/martincostello/dotnet-minimal-api-integration-testing/blob/b90edcc53d8c6376b9445d946a65bfcfef7187e1/.github/workflows/build.yml#L16

**Comment by programatt** [comment]
@martincostello Thanks for the tip! I actually opened up a PR on Playwright to get it to .NET 6, but looks like there's a reason why it wasn't done already! Hehe.
