### ISSUE TITLE
Impostor Repository

### ISSUE THREAD

**Issue by freezy** [martincostello/dotnet-minimal-api-integration-testing#526]
Hi, just letting you know that https://github.com/ilromali/dotnet-minimal-api-integration-testing cloned your repo, replaced the author in your commits with his, and re-published it as his own. Did the same with mine, I just asked him to delete it, not sure what else there is to do. Cheers.

**Comment by martincostello** [comment]
Yeah I spotted that at the time. 

They weren’t diligent enough to actually update all the various bits of content that shows where it really came from though if you know where to look (like the readme…) 😄

Thanks for reaching out though 👍

**Comment by freezy** [comment]
I just opened an issue in their repo asking to delete it, and they did.
Might be worth a try.
