### ISSUE TITLE
Starting TestServer?

### ISSUE THREAD

**Issue by b5white** [martincostello/dotnet-minimal-api-integration-testing#866]
In HttpServerFixture, CreateHost, line 87,
//   testHost.Start();
I found that while I do have to return the testHost to keep the system happy, I don't actually have to start it. My tests (only 3 so far) now run almost twice as fast.
I assume you are using more features, than I, so you may need it started. But the ToDo tests all run.
HTH, Brad

**Comment by martincostello** [comment]
Thanks for the suggestion! I've made this change in #887.
